### ISSUE TITLE
请问如何订阅插件？

### ISSUE THREAD

**Issue by MrEbonycat** [Goshin/Buka-Darkness#2]
用手机浏览器打开http://sited.noear.org ， 点击“安装”按钮没有反应。
安装按钮的链接是以“sited://”开头的，请问如何转换成“http://”开头的，可以直接在Buka_Darkness内使用的订阅源？

**Comment by Goshin** [comment]
你可以尝试解析一下 `sited://` 链接，`data?` 后面就是编码后的链接的主要内容。

**Comment by MrEbonycat** [comment]
BASE64解码成功，感谢。
